language: node_js

sudo: false

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

env:
  - MONGODB_VERSION="3.2.5"
  - MONGODB_VERSION="3.0.11"
  - MONGODB_VERSION="2.6.12"
  - MONGODB_VERSION="3.6.3"

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 5
